name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: My Actions
        uses: ./.github/actions/action.yml
      - name: install packages
        run: make install
      - name: format
        run: make format
      - name: lint
        run: make lint
      - name: test
        run: make test